# .pre-commit-config.yaml

# Define the minimum version of pre-commit required
minimum_pre_commit_version: "2.17.0"

# Repositories and hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 23.9.1 # Use the latest stable version
    hooks:
      - id: black
        language_version: python3 # Adjust to your Python version

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0 # Use the latest stable version
    hooks:
      - id: prettier

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
